(function(angular) {
	angular.module('scHelper').filter('express', function() {
		return function(one) {
			var express = {
				"ZTKY": "中铁物流",
				"GTO": "国通快递",
				"QFKD": "全峰快递",
				"shentong": "申通快递",
				"RRS": "日日顺物流",
				"ANJELEX": "安捷",
				"shunfeng": "顺丰",
				"HQKY": "华企",
				"XBWL": "新邦",
				"YCGWL": "远成",
				"YIMIDIDA": "壹米滴答",
				"UPS": "UPS",
				"TNT": "TNT",
				"DEPPON": "德邦快递",
				"HREX": "锦程快递",
				"ARAMEX": "Aramex",
				"YXWL": "宇鑫物流",
				"SHENGHUI": "盛辉",
				"DPEX": "DPEX",
				"FEDEX": "FEDEX",
				"ZJS": "宅急送",
				"ANXINDA": "安信达",
				"DEXP": "D速",
				"JOUST": "急先达",
				"PHOENIXEXP": "凤凰",
				"SURE": "速尔",
				"VANGEN": "万庚",
				"FTD": "富腾达",
				"EWINSHINE": "万象",
				"KYEXPRESS": "跨越",
				"JD": "京东快递",
				"APEX": "全一",
				"KERRY": "嘉里物流",
				"JIAYI": "佳怡",
				"DHL": "DHL",
				"EFSPOST": "平安快递",
				"SFWL": "盛丰",
				"SFC": "三态",
				"ZTO": "中通快递",
				"HYE": "鸿远",
				"TTKDEX": "天天",
				"COE": "中国东方",
				"HOAU": "天地华宇",
				"HTKY": "百世快递",
				"BSKY": "百世快运",
				"SUNING": "苏宁",
				"FEDEXIN": "FedEx国际",
				"AAEWEB": "AAE",
				"FASTEXPRESS": "快捷",
				"ETD": "易通达",
				"XFEXPRESS": "信丰",
				"YFEXPRESS": "越丰",
				"YIEXPRESS": "宜送",
				"DJ56": "东骏快捷",
				"UC56": "优速快递",
				"LBEX": "龙邦快递",
				"PEWKEE": "晋越",
				"RFD": "如风达",
				"GZWENJIE": "文捷航空",
				"JIAJI": "佳吉",
				"YTO": "圆通快递",
				"YUNDA": "韵达快递",
				"CAE": "民航",
				"YTEXPRESS": "运通",
				"EMS": "EMS(国内和国际)",
				"ZTO56": "中通快运(物流)",
				"PCA": "PCA",
				"WANJIA": "万家物流",
				"EES": "百福东方",
				"HENGLU": "恒路",
				"BROADASIA": "亚风",
				"CHINZ56": "秦远物流",
				"CRE": "中铁快运",
				"ANE": "安能快递",
				"CNPL": "中邮",
				"ZMKMEX": "芝麻开门",
				"BLUESKY": "蓝天",
				"DTW": "大田",
				"YFHEX": "原飞航",
				"LTS": "联昊通",
				"PEISI": "配思航宇",
				"QCKD": "全晨",
				"EWE": "EWE",
				"ANEEX": "安能快递",
				"GSD": "共速达",
				"QEXPRESS": "易达通",
				"SDEX": "顺达快递",
				"KKE": "京广快递",
				"GCE": "飞洋",
				"JIUYESCM": "九曳供应链",
				"YADEX": "源安达",
				"CHINAPOST": "邮政包裹",
				"ND56": "能达",
				"PJKD": "品俊快递",
				"BLACKDOG": "黑狗",
				"FLYWAYEX": "程光",
				"TMS": "加运美"
			}
			return express[one]
		}
	});
})(angular);

//			var express = {
//				"ZTKY": "中铁物流",
//				"GTO": "国通快递",
//				"QFKD": "全峰快递",
//				"STO": "申通快递",
//				"RRS": "日日顺物流",
//				"ANJELEX": "安捷",
//				"SFEXPRESS": "顺丰",
//				"HQKY": "华企",
//				"XBWL": "新邦",
//				"YCGWL": "远成",
//				"YIMIDIDA": "壹米滴答",
//				"UPS": "UPS",
//				"TNT": "TNT",
//				"DEPPON": "德邦快递",
//				"HREX": "锦程快递",
//				"ARAMEX": "Aramex",
//				"YXWL": "宇鑫物流",
//				"SHENGHUI": "盛辉",
//				"DPEX": "DPEX",
//				"FEDEX": "FEDEX",
//				"ZJS": "宅急送",
//				"ANXINDA": "安信达",
//				"DEXP": "D速",
//				"JOUST": "急先达",
//				"PHOENIXEXP": "凤凰",
//				"SURE": "速尔",
//				"VANGEN": "万庚",
//				"FTD": "富腾达",
//				"EWINSHINE": "万象",
//				"KYEXPRESS": "跨越",
//				"JD": "京东快递",
//				"APEX": "全一",
//				"KERRY": "嘉里物流",
//				"JIAYI": "佳怡",
//				"DHL": "DHL",
//				"EFSPOST": "平安快递",
//				"SFWL": "盛丰",
//				"SFC": "三态",
//				"ZTO": "中通快递",
//				"HYE": "鸿远",
//				"TTKDEX": "天天",
//				"COE": "中国东方",
//				"HOAU": "天地华宇",
//				"HTKY": "百世快递",
//				"BSKY": "百世快运",
//				"SUNING": "苏宁",
//				"FEDEXIN": "FedEx国际",
//				"AAEWEB": "AAE",
//				"FASTEXPRESS": "快捷",
//				"ETD": "易通达",
//				"XFEXPRESS": "信丰",
//				"YFEXPRESS": "越丰",
//				"YIEXPRESS": "宜送",
//				"DJ56": "东骏快捷",
//				"UC56": "优速快递",
//				"LBEX": "龙邦快递",
//				"PEWKEE": "晋越",
//				"RFD": "如风达",
//				"GZWENJIE": "文捷航空",
//				"JIAJI": "佳吉",
//				"YTO": "圆通快递",
//				"YUNDA": "韵达快递",
//				"CAE": "民航",
//				"YTEXPRESS": "运通",
//				"EMS": "EMS(国内和国际)",
//				"ZTO56": "中通快运(物流)",
//				"PCA": "PCA",
//				"WANJIA": "万家物流",
//				"EES": "百福东方",
//				"HENGLU": "恒路",
//				"BROADASIA": "亚风",
//				"CHINZ56": "秦远物流",
//				"CRE": "中铁快运",
//				"ANE": "安能快递",
//				"CNPL": "中邮",
//				"ZMKMEX": "芝麻开门",
//				"BLUESKY": "蓝天",
//				"DTW": "大田",
//				"YFHEX": "原飞航",
//				"LTS": "联昊通",
//				"PEISI": "配思航宇",
//				"QCKD": "全晨",
//				"EWE": "EWE",
//				"ANEEX": "安能快递",
//				"GSD": "共速达",
//				"QEXPRESS": "易达通",
//				"SDEX": "顺达快递",
//				"KKE": "京广快递",
//				"GCE": "飞洋",
//				"JIUYESCM": "九曳供应链",
//				"YADEX": "源安达",
//				"CHINAPOST": "邮政包裹",
//				"ND56": "能达",
//				"PJKD": "品俊快递",
//				"BLACKDOG": "黑狗",
//				"FLYWAYEX": "程光",
//				"TMS": "加运美"
//			}